version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg18
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: project_farm
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./db/init:/docker-entrypoint-initdb.d

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    entrypoint: ["bash", "-c", "ollama serve & sleep 3 && ollama pull nomic-embed-text && tail -f /dev/null"]

  images:
    build: ./Images
    container_name: images
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

  announcements:
    build: ./Announcements
    container_name: announcements
    restart: unless-stopped
    depends_on:
      - db
      - ollama
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123
      DB_NAME: project_farm
      OLLAMA_HOST: http://ollama:11434
      IMAGES_SERVICE_EXTERNAL_CONNECTIONS: http://localhost:8080/images/

  messenger:
    build: ./Messenger
    container_name: messenger
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123
      DB_NAME: project_farm


  users:
    build: ./Users
    container_name: users
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123
      DB_NAME: project_farm
      OLLAMA_HOST: http://ollama:11434

  main:
    build: ./Main
    container_name: main
    restart: unless-stopped
    ports:
      - "443:443"
    depends_on:
      - db
      - ollama
      - images
      - announcements
      - users
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123
      DB_NAME: project_farm
      IMAGES_SERVICE_HOST_GRPC_PORT: images:8086
      ANNOUNCEMENTS_SERVICE_HOST_GRPC_PORT: announcements:8086
      MESSENGER_SERVICE_HOST_GRPC_PORT: messenger:8086
      USERS_SERVICE_HOST_GRPC_PORT: users:8086

volumes:
  postgres_data:
  ollama: