// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0--rc1
// source: messenger.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int32                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatsRequest) Reset() {
	*x = GetChatsRequest{}
	mi := &file_messenger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatsRequest) ProtoMessage() {}

func (x *GetChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatsRequest.ProtoReflect.Descriptor instead.
func (*GetChatsRequest) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{0}
}

func (x *GetChatsRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type GetChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*ChatInfo            `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatsResponse) Reset() {
	*x = GetChatsResponse{}
	mi := &file_messenger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatsResponse) ProtoMessage() {}

func (x *GetChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatsResponse.ProtoReflect.Descriptor instead.
func (*GetChatsResponse) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{1}
}

func (x *GetChatsResponse) GetChats() []*ChatInfo {
	if x != nil {
		return x.Chats
	}
	return nil
}

type ChatInfo struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	PartnerID                int32                  `protobuf:"varint,1,opt,name=partnerID,proto3" json:"partnerID,omitempty"`
	PartnerName              string                 `protobuf:"bytes,2,opt,name=partnerName,proto3" json:"partnerName,omitempty"`
	RelatedAnnouncementTitle string                 `protobuf:"bytes,3,opt,name=relatedAnnouncementTitle,proto3" json:"relatedAnnouncementTitle,omitempty"`
	PartnerAvatarPath        string                 `protobuf:"bytes,4,opt,name=partnerAvatarPath,proto3" json:"partnerAvatarPath,omitempty"`
	RelatedAnnouncementID    int32                  `protobuf:"varint,5,opt,name=relatedAnnouncementID,proto3" json:"relatedAnnouncementID,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ChatInfo) Reset() {
	*x = ChatInfo{}
	mi := &file_messenger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatInfo) ProtoMessage() {}

func (x *ChatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatInfo.ProtoReflect.Descriptor instead.
func (*ChatInfo) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{2}
}

func (x *ChatInfo) GetPartnerID() int32 {
	if x != nil {
		return x.PartnerID
	}
	return 0
}

func (x *ChatInfo) GetPartnerName() string {
	if x != nil {
		return x.PartnerName
	}
	return ""
}

func (x *ChatInfo) GetRelatedAnnouncementTitle() string {
	if x != nil {
		return x.RelatedAnnouncementTitle
	}
	return ""
}

func (x *ChatInfo) GetPartnerAvatarPath() string {
	if x != nil {
		return x.PartnerAvatarPath
	}
	return ""
}

func (x *ChatInfo) GetRelatedAnnouncementID() int32 {
	if x != nil {
		return x.RelatedAnnouncementID
	}
	return 0
}

type SendMessageRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ReceivedID            int32                  `protobuf:"varint,1,opt,name=receivedID,proto3" json:"receivedID,omitempty"`
	SenderID              int32                  `protobuf:"varint,2,opt,name=senderID,proto3" json:"senderID,omitempty"`
	RelatedAnnouncementID int32                  `protobuf:"varint,3,opt,name=relatedAnnouncementID,proto3" json:"relatedAnnouncementID,omitempty"`
	Text                  string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_messenger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{3}
}

func (x *SendMessageRequest) GetReceivedID() int32 {
	if x != nil {
		return x.ReceivedID
	}
	return 0
}

func (x *SendMessageRequest) GetSenderID() int32 {
	if x != nil {
		return x.SenderID
	}
	return 0
}

func (x *SendMessageRequest) GetRelatedAnnouncementID() int32 {
	if x != nil {
		return x.RelatedAnnouncementID
	}
	return 0
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_messenger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{4}
}

type GetChatHistoryRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PartnerID             int32                  `protobuf:"varint,1,opt,name=partnerID,proto3" json:"partnerID,omitempty"`
	UserID                int32                  `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	RelatedAnnouncementID int32                  `protobuf:"varint,3,opt,name=relatedAnnouncementID,proto3" json:"relatedAnnouncementID,omitempty"`
	Offset                int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetChatHistoryRequest) Reset() {
	*x = GetChatHistoryRequest{}
	mi := &file_messenger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryRequest) ProtoMessage() {}

func (x *GetChatHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetChatHistoryRequest) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{5}
}

func (x *GetChatHistoryRequest) GetPartnerID() int32 {
	if x != nil {
		return x.PartnerID
	}
	return 0
}

func (x *GetChatHistoryRequest) GetUserID() int32 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GetChatHistoryRequest) GetRelatedAnnouncementID() int32 {
	if x != nil {
		return x.RelatedAnnouncementID
	}
	return 0
}

func (x *GetChatHistoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetChatHistoryResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Messages      []*GetChatHistoryMessage `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryResponse) Reset() {
	*x = GetChatHistoryResponse{}
	mi := &file_messenger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryResponse) ProtoMessage() {}

func (x *GetChatHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetChatHistoryResponse) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{6}
}

func (x *GetChatHistoryResponse) GetMessages() []*GetChatHistoryMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type GetChatHistoryMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	MyMessage     bool                   `protobuf:"varint,2,opt,name=myMessage,proto3" json:"myMessage,omitempty"`
	CreateAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=createAt,proto3" json:"createAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChatHistoryMessage) Reset() {
	*x = GetChatHistoryMessage{}
	mi := &file_messenger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChatHistoryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChatHistoryMessage) ProtoMessage() {}

func (x *GetChatHistoryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messenger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChatHistoryMessage.ProtoReflect.Descriptor instead.
func (*GetChatHistoryMessage) Descriptor() ([]byte, []int) {
	return file_messenger_proto_rawDescGZIP(), []int{7}
}

func (x *GetChatHistoryMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GetChatHistoryMessage) GetMyMessage() bool {
	if x != nil {
		return x.MyMessage
	}
	return false
}

func (x *GetChatHistoryMessage) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

var File_messenger_proto protoreflect.FileDescriptor

const file_messenger_proto_rawDesc = "" +
	"\n" +
	"\x0fmessenger.proto\x12\tmessenger\x1a\x0ftimestamp.proto\")\n" +
	"\x0fGetChatsRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x05R\x06userID\"=\n" +
	"\x10GetChatsResponse\x12)\n" +
	"\x05chats\x18\x01 \x03(\v2\x13.messenger.ChatInfoR\x05chats\"\xea\x01\n" +
	"\bChatInfo\x12\x1c\n" +
	"\tpartnerID\x18\x01 \x01(\x05R\tpartnerID\x12 \n" +
	"\vpartnerName\x18\x02 \x01(\tR\vpartnerName\x12:\n" +
	"\x18relatedAnnouncementTitle\x18\x03 \x01(\tR\x18relatedAnnouncementTitle\x12,\n" +
	"\x11partnerAvatarPath\x18\x04 \x01(\tR\x11partnerAvatarPath\x124\n" +
	"\x15relatedAnnouncementID\x18\x05 \x01(\x05R\x15relatedAnnouncementID\"\x9a\x01\n" +
	"\x12SendMessageRequest\x12\x1e\n" +
	"\n" +
	"receivedID\x18\x01 \x01(\x05R\n" +
	"receivedID\x12\x1a\n" +
	"\bsenderID\x18\x02 \x01(\x05R\bsenderID\x124\n" +
	"\x15relatedAnnouncementID\x18\x03 \x01(\x05R\x15relatedAnnouncementID\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"\x15\n" +
	"\x13SendMessageResponse\"\x9b\x01\n" +
	"\x15GetChatHistoryRequest\x12\x1c\n" +
	"\tpartnerID\x18\x01 \x01(\x05R\tpartnerID\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\x05R\x06userID\x124\n" +
	"\x15relatedAnnouncementID\x18\x03 \x01(\x05R\x15relatedAnnouncementID\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"V\n" +
	"\x16GetChatHistoryResponse\x12<\n" +
	"\bmessages\x18\x01 \x03(\v2 .messenger.GetChatHistoryMessageR\bmessages\"\x81\x01\n" +
	"\x15GetChatHistoryMessage\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1c\n" +
	"\tmyMessage\x18\x02 \x01(\bR\tmyMessage\x126\n" +
	"\bcreateAt\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bcreateAt2\xf5\x01\n" +
	"\tMessenger\x12C\n" +
	"\bGetChats\x12\x1a.messenger.GetChatsRequest\x1a\x1b.messenger.GetChatsResponse\x12L\n" +
	"\vSendMessage\x12\x1d.messenger.SendMessageRequest\x1a\x1e.messenger.SendMessageResponse\x12U\n" +
	"\x0eGetChatHistory\x12 .messenger.GetChatHistoryRequest\x1a!.messenger.GetChatHistoryResponseB\x03Z\x01.b\x06proto3"

var (
	file_messenger_proto_rawDescOnce sync.Once
	file_messenger_proto_rawDescData []byte
)

func file_messenger_proto_rawDescGZIP() []byte {
	file_messenger_proto_rawDescOnce.Do(func() {
		file_messenger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messenger_proto_rawDesc), len(file_messenger_proto_rawDesc)))
	})
	return file_messenger_proto_rawDescData
}

var file_messenger_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_messenger_proto_goTypes = []any{
	(*GetChatsRequest)(nil),        // 0: messenger.GetChatsRequest
	(*GetChatsResponse)(nil),       // 1: messenger.GetChatsResponse
	(*ChatInfo)(nil),               // 2: messenger.ChatInfo
	(*SendMessageRequest)(nil),     // 3: messenger.SendMessageRequest
	(*SendMessageResponse)(nil),    // 4: messenger.SendMessageResponse
	(*GetChatHistoryRequest)(nil),  // 5: messenger.GetChatHistoryRequest
	(*GetChatHistoryResponse)(nil), // 6: messenger.GetChatHistoryResponse
	(*GetChatHistoryMessage)(nil),  // 7: messenger.GetChatHistoryMessage
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
}
var file_messenger_proto_depIdxs = []int32{
	2, // 0: messenger.GetChatsResponse.chats:type_name -> messenger.ChatInfo
	7, // 1: messenger.GetChatHistoryResponse.messages:type_name -> messenger.GetChatHistoryMessage
	8, // 2: messenger.GetChatHistoryMessage.createAt:type_name -> google.protobuf.Timestamp
	0, // 3: messenger.Messenger.GetChats:input_type -> messenger.GetChatsRequest
	3, // 4: messenger.Messenger.SendMessage:input_type -> messenger.SendMessageRequest
	5, // 5: messenger.Messenger.GetChatHistory:input_type -> messenger.GetChatHistoryRequest
	1, // 6: messenger.Messenger.GetChats:output_type -> messenger.GetChatsResponse
	4, // 7: messenger.Messenger.SendMessage:output_type -> messenger.SendMessageResponse
	6, // 8: messenger.Messenger.GetChatHistory:output_type -> messenger.GetChatHistoryResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_messenger_proto_init() }
func file_messenger_proto_init() {
	if File_messenger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messenger_proto_rawDesc), len(file_messenger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_messenger_proto_goTypes,
		DependencyIndexes: file_messenger_proto_depIdxs,
		MessageInfos:      file_messenger_proto_msgTypes,
	}.Build()
	File_messenger_proto = out.File
	file_messenger_proto_goTypes = nil
	file_messenger_proto_depIdxs = nil
}
