// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0--rc1
// source: announcements.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchAnnouncementsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Offset         int32                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	UserID         string                 `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	SearchString   string                 `protobuf:"bytes,3,opt,name=searchString,proto3" json:"searchString,omitempty"`
	Category       string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Orderby        string                 `protobuf:"bytes,5,opt,name=orderby,proto3" json:"orderby,omitempty"`
	AnnouncementID int32                  `protobuf:"varint,6,opt,name=announcementID,proto3" json:"announcementID,omitempty"`
	AuthorID       string                 `protobuf:"bytes,7,opt,name=authorID,proto3" json:"authorID,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchAnnouncementsRequest) Reset() {
	*x = SearchAnnouncementsRequest{}
	mi := &file_announcements_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAnnouncementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAnnouncementsRequest) ProtoMessage() {}

func (x *SearchAnnouncementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_announcements_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAnnouncementsRequest.ProtoReflect.Descriptor instead.
func (*SearchAnnouncementsRequest) Descriptor() ([]byte, []int) {
	return file_announcements_proto_rawDescGZIP(), []int{0}
}

func (x *SearchAnnouncementsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchAnnouncementsRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *SearchAnnouncementsRequest) GetSearchString() string {
	if x != nil {
		return x.SearchString
	}
	return ""
}

func (x *SearchAnnouncementsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SearchAnnouncementsRequest) GetOrderby() string {
	if x != nil {
		return x.Orderby
	}
	return ""
}

func (x *SearchAnnouncementsRequest) GetAnnouncementID() int32 {
	if x != nil {
		return x.AnnouncementID
	}
	return 0
}

func (x *SearchAnnouncementsRequest) GetAuthorID() string {
	if x != nil {
		return x.AuthorID
	}
	return ""
}

type SearchAnnouncementsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AnnouncementsData []*AnnouncementData    `protobuf:"bytes,1,rep,name=announcementsData,proto3" json:"announcementsData,omitempty"`
	Error             string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SearchAnnouncementsResponse) Reset() {
	*x = SearchAnnouncementsResponse{}
	mi := &file_announcements_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAnnouncementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAnnouncementsResponse) ProtoMessage() {}

func (x *SearchAnnouncementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_announcements_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAnnouncementsResponse.ProtoReflect.Descriptor instead.
func (*SearchAnnouncementsResponse) Descriptor() ([]byte, []int) {
	return file_announcements_proto_rawDescGZIP(), []int{1}
}

func (x *SearchAnnouncementsResponse) GetAnnouncementsData() []*AnnouncementData {
	if x != nil {
		return x.AnnouncementsData
	}
	return nil
}

func (x *SearchAnnouncementsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AnnouncementData struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AuthorName         string                 `protobuf:"bytes,1,opt,name=authorName,proto3" json:"authorName,omitempty"`
	AuthorID           int32                  `protobuf:"varint,2,opt,name=authorID,proto3" json:"authorID,omitempty"`
	Title              string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description        string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Category           string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	LinkToAnnouncement string                 `protobuf:"bytes,6,opt,name=linkToAnnouncement,proto3" json:"linkToAnnouncement,omitempty"`
	AnnouncementID     int32                  `protobuf:"varint,7,opt,name=announcementID,proto3" json:"announcementID,omitempty"`
	Images             []string               `protobuf:"bytes,8,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AnnouncementData) Reset() {
	*x = AnnouncementData{}
	mi := &file_announcements_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnnouncementData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnnouncementData) ProtoMessage() {}

func (x *AnnouncementData) ProtoReflect() protoreflect.Message {
	mi := &file_announcements_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnnouncementData.ProtoReflect.Descriptor instead.
func (*AnnouncementData) Descriptor() ([]byte, []int) {
	return file_announcements_proto_rawDescGZIP(), []int{2}
}

func (x *AnnouncementData) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

func (x *AnnouncementData) GetAuthorID() int32 {
	if x != nil {
		return x.AuthorID
	}
	return 0
}

func (x *AnnouncementData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AnnouncementData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AnnouncementData) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *AnnouncementData) GetLinkToAnnouncement() string {
	if x != nil {
		return x.LinkToAnnouncement
	}
	return ""
}

func (x *AnnouncementData) GetAnnouncementID() int32 {
	if x != nil {
		return x.AnnouncementID
	}
	return 0
}

func (x *AnnouncementData) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type CreateAnnouncementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	AuthorID      string                 `protobuf:"bytes,4,opt,name=authorID,proto3" json:"authorID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAnnouncementRequest) Reset() {
	*x = CreateAnnouncementRequest{}
	mi := &file_announcements_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnnouncementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnnouncementRequest) ProtoMessage() {}

func (x *CreateAnnouncementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_announcements_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnnouncementRequest.ProtoReflect.Descriptor instead.
func (*CreateAnnouncementRequest) Descriptor() ([]byte, []int) {
	return file_announcements_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAnnouncementRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateAnnouncementRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAnnouncementRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateAnnouncementRequest) GetAuthorID() string {
	if x != nil {
		return x.AuthorID
	}
	return ""
}

type CreateAnnouncementResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Error          string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	AnnouncementID int32                  `protobuf:"varint,2,opt,name=announcementID,proto3" json:"announcementID,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAnnouncementResponse) Reset() {
	*x = CreateAnnouncementResponse{}
	mi := &file_announcements_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAnnouncementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnnouncementResponse) ProtoMessage() {}

func (x *CreateAnnouncementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_announcements_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnnouncementResponse.ProtoReflect.Descriptor instead.
func (*CreateAnnouncementResponse) Descriptor() ([]byte, []int) {
	return file_announcements_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAnnouncementResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateAnnouncementResponse) GetAnnouncementID() int32 {
	if x != nil {
		return x.AnnouncementID
	}
	return 0
}

type AddImagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ImagesPath     []string               `protobuf:"bytes,1,rep,name=imagesPath,proto3" json:"imagesPath,omitempty"`
	AnnouncementID int32                  `protobuf:"varint,2,opt,name=announcementID,proto3" json:"announcementID,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddImagesRequest) Reset() {
	*x = AddImagesRequest{}
	mi := &file_announcements_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddImagesRequest) ProtoMessage() {}

func (x *AddImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_announcements_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddImagesRequest.ProtoReflect.Descriptor instead.
func (*AddImagesRequest) Descriptor() ([]byte, []int) {
	return file_announcements_proto_rawDescGZIP(), []int{5}
}

func (x *AddImagesRequest) GetImagesPath() []string {
	if x != nil {
		return x.ImagesPath
	}
	return nil
}

func (x *AddImagesRequest) GetAnnouncementID() int32 {
	if x != nil {
		return x.AnnouncementID
	}
	return 0
}

type AddImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddImagesResponse) Reset() {
	*x = AddImagesResponse{}
	mi := &file_announcements_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddImagesResponse) ProtoMessage() {}

func (x *AddImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_announcements_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddImagesResponse.ProtoReflect.Descriptor instead.
func (*AddImagesResponse) Descriptor() ([]byte, []int) {
	return file_announcements_proto_rawDescGZIP(), []int{6}
}

func (x *AddImagesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteAnnouncementRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AnnouncementID int32                  `protobuf:"varint,1,opt,name=announcementID,proto3" json:"announcementID,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteAnnouncementRequest) Reset() {
	*x = DeleteAnnouncementRequest{}
	mi := &file_announcements_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAnnouncementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAnnouncementRequest) ProtoMessage() {}

func (x *DeleteAnnouncementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_announcements_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAnnouncementRequest.ProtoReflect.Descriptor instead.
func (*DeleteAnnouncementRequest) Descriptor() ([]byte, []int) {
	return file_announcements_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAnnouncementRequest) GetAnnouncementID() int32 {
	if x != nil {
		return x.AnnouncementID
	}
	return 0
}

type DeleteAnnouncementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAnnouncementResponse) Reset() {
	*x = DeleteAnnouncementResponse{}
	mi := &file_announcements_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAnnouncementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAnnouncementResponse) ProtoMessage() {}

func (x *DeleteAnnouncementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_announcements_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAnnouncementResponse.ProtoReflect.Descriptor instead.
func (*DeleteAnnouncementResponse) Descriptor() ([]byte, []int) {
	return file_announcements_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAnnouncementResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_announcements_proto protoreflect.FileDescriptor

const file_announcements_proto_rawDesc = "" +
	"\n" +
	"\x13announcements.proto\x12\rannouncements\"\xea\x01\n" +
	"\x1aSearchAnnouncementsRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\tR\x06userID\x12\"\n" +
	"\fsearchString\x18\x03 \x01(\tR\fsearchString\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x18\n" +
	"\aorderby\x18\x05 \x01(\tR\aorderby\x12&\n" +
	"\x0eannouncementID\x18\x06 \x01(\x05R\x0eannouncementID\x12\x1a\n" +
	"\bauthorID\x18\a \x01(\tR\bauthorID\"\x82\x01\n" +
	"\x1bSearchAnnouncementsResponse\x12M\n" +
	"\x11announcementsData\x18\x01 \x03(\v2\x1f.announcements.AnnouncementDataR\x11announcementsData\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x92\x02\n" +
	"\x10AnnouncementData\x12\x1e\n" +
	"\n" +
	"authorName\x18\x01 \x01(\tR\n" +
	"authorName\x12\x1a\n" +
	"\bauthorID\x18\x02 \x01(\x05R\bauthorID\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12.\n" +
	"\x12linkToAnnouncement\x18\x06 \x01(\tR\x12linkToAnnouncement\x12&\n" +
	"\x0eannouncementID\x18\a \x01(\x05R\x0eannouncementID\x12\x16\n" +
	"\x06images\x18\b \x03(\tR\x06images\"\x8b\x01\n" +
	"\x19CreateAnnouncementRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1a\n" +
	"\bauthorID\x18\x04 \x01(\tR\bauthorID\"Z\n" +
	"\x1aCreateAnnouncementResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12&\n" +
	"\x0eannouncementID\x18\x02 \x01(\x05R\x0eannouncementID\"Z\n" +
	"\x10AddImagesRequest\x12\x1e\n" +
	"\n" +
	"imagesPath\x18\x01 \x03(\tR\n" +
	"imagesPath\x12&\n" +
	"\x0eannouncementID\x18\x02 \x01(\x05R\x0eannouncementID\")\n" +
	"\x11AddImagesResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"C\n" +
	"\x19DeleteAnnouncementRequest\x12&\n" +
	"\x0eannouncementID\x18\x01 \x01(\x05R\x0eannouncementID\"2\n" +
	"\x1aDeleteAnnouncementResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\xa9\x03\n" +
	"\rAnnouncements\x12n\n" +
	"\x13SearchAnnouncements\x12).announcements.SearchAnnouncementsRequest\x1a*.announcements.SearchAnnouncementsResponse(\x01\x12k\n" +
	"\x12CreateAnnouncement\x12(.announcements.CreateAnnouncementRequest\x1a).announcements.CreateAnnouncementResponse(\x01\x12P\n" +
	"\tAddImages\x12\x1f.announcements.AddImagesRequest\x1a .announcements.AddImagesResponse(\x01\x12i\n" +
	"\x12DeleteAnnouncement\x12(.announcements.DeleteAnnouncementRequest\x1a).announcements.DeleteAnnouncementResponseB\x03Z\x01.b\x06proto3"

var (
	file_announcements_proto_rawDescOnce sync.Once
	file_announcements_proto_rawDescData []byte
)

func file_announcements_proto_rawDescGZIP() []byte {
	file_announcements_proto_rawDescOnce.Do(func() {
		file_announcements_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_announcements_proto_rawDesc), len(file_announcements_proto_rawDesc)))
	})
	return file_announcements_proto_rawDescData
}

var file_announcements_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_announcements_proto_goTypes = []any{
	(*SearchAnnouncementsRequest)(nil),  // 0: announcements.SearchAnnouncementsRequest
	(*SearchAnnouncementsResponse)(nil), // 1: announcements.SearchAnnouncementsResponse
	(*AnnouncementData)(nil),            // 2: announcements.AnnouncementData
	(*CreateAnnouncementRequest)(nil),   // 3: announcements.CreateAnnouncementRequest
	(*CreateAnnouncementResponse)(nil),  // 4: announcements.CreateAnnouncementResponse
	(*AddImagesRequest)(nil),            // 5: announcements.AddImagesRequest
	(*AddImagesResponse)(nil),           // 6: announcements.AddImagesResponse
	(*DeleteAnnouncementRequest)(nil),   // 7: announcements.DeleteAnnouncementRequest
	(*DeleteAnnouncementResponse)(nil),  // 8: announcements.DeleteAnnouncementResponse
}
var file_announcements_proto_depIdxs = []int32{
	2, // 0: announcements.SearchAnnouncementsResponse.announcementsData:type_name -> announcements.AnnouncementData
	0, // 1: announcements.Announcements.SearchAnnouncements:input_type -> announcements.SearchAnnouncementsRequest
	3, // 2: announcements.Announcements.CreateAnnouncement:input_type -> announcements.CreateAnnouncementRequest
	5, // 3: announcements.Announcements.AddImages:input_type -> announcements.AddImagesRequest
	7, // 4: announcements.Announcements.DeleteAnnouncement:input_type -> announcements.DeleteAnnouncementRequest
	1, // 5: announcements.Announcements.SearchAnnouncements:output_type -> announcements.SearchAnnouncementsResponse
	4, // 6: announcements.Announcements.CreateAnnouncement:output_type -> announcements.CreateAnnouncementResponse
	6, // 7: announcements.Announcements.AddImages:output_type -> announcements.AddImagesResponse
	8, // 8: announcements.Announcements.DeleteAnnouncement:output_type -> announcements.DeleteAnnouncementResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_announcements_proto_init() }
func file_announcements_proto_init() {
	if File_announcements_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_announcements_proto_rawDesc), len(file_announcements_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_announcements_proto_goTypes,
		DependencyIndexes: file_announcements_proto_depIdxs,
		MessageInfos:      file_announcements_proto_msgTypes,
	}.Build()
	File_announcements_proto = out.File
	file_announcements_proto_goTypes = nil
	file_announcements_proto_depIdxs = nil
}
