// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0--rc1
// source: announcements.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Announcements_SearchAnnouncements_FullMethodName = "/announcements.Announcements/SearchAnnouncements"
	Announcements_CreateAnnouncement_FullMethodName  = "/announcements.Announcements/CreateAnnouncement"
	Announcements_AddImages_FullMethodName           = "/announcements.Announcements/AddImages"
	Announcements_DeleteAnnouncement_FullMethodName  = "/announcements.Announcements/DeleteAnnouncement"
)

// AnnouncementsClient is the client API for Announcements service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnnouncementsClient interface {
	SearchAnnouncements(ctx context.Context, in *SearchAnnouncementsRequest, opts ...grpc.CallOption) (*SearchAnnouncementsResponse, error)
	CreateAnnouncement(ctx context.Context, in *CreateAnnouncementRequest, opts ...grpc.CallOption) (*CreateAnnouncementResponse, error)
	AddImages(ctx context.Context, in *AddImagesRequest, opts ...grpc.CallOption) (*AddImagesResponse, error)
	DeleteAnnouncement(ctx context.Context, in *DeleteAnnouncementRequest, opts ...grpc.CallOption) (*DeleteAnnouncementResponse, error)
}

type announcementsClient struct {
	cc grpc.ClientConnInterface
}

func NewAnnouncementsClient(cc grpc.ClientConnInterface) AnnouncementsClient {
	return &announcementsClient{cc}
}

func (c *announcementsClient) SearchAnnouncements(ctx context.Context, in *SearchAnnouncementsRequest, opts ...grpc.CallOption) (*SearchAnnouncementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchAnnouncementsResponse)
	err := c.cc.Invoke(ctx, Announcements_SearchAnnouncements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *announcementsClient) CreateAnnouncement(ctx context.Context, in *CreateAnnouncementRequest, opts ...grpc.CallOption) (*CreateAnnouncementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAnnouncementResponse)
	err := c.cc.Invoke(ctx, Announcements_CreateAnnouncement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *announcementsClient) AddImages(ctx context.Context, in *AddImagesRequest, opts ...grpc.CallOption) (*AddImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddImagesResponse)
	err := c.cc.Invoke(ctx, Announcements_AddImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *announcementsClient) DeleteAnnouncement(ctx context.Context, in *DeleteAnnouncementRequest, opts ...grpc.CallOption) (*DeleteAnnouncementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAnnouncementResponse)
	err := c.cc.Invoke(ctx, Announcements_DeleteAnnouncement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnnouncementsServer is the server API for Announcements service.
// All implementations must embed UnimplementedAnnouncementsServer
// for forward compatibility.
type AnnouncementsServer interface {
	SearchAnnouncements(context.Context, *SearchAnnouncementsRequest) (*SearchAnnouncementsResponse, error)
	CreateAnnouncement(context.Context, *CreateAnnouncementRequest) (*CreateAnnouncementResponse, error)
	AddImages(context.Context, *AddImagesRequest) (*AddImagesResponse, error)
	DeleteAnnouncement(context.Context, *DeleteAnnouncementRequest) (*DeleteAnnouncementResponse, error)
	mustEmbedUnimplementedAnnouncementsServer()
}

// UnimplementedAnnouncementsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnnouncementsServer struct{}

func (UnimplementedAnnouncementsServer) SearchAnnouncements(context.Context, *SearchAnnouncementsRequest) (*SearchAnnouncementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchAnnouncements not implemented")
}
func (UnimplementedAnnouncementsServer) CreateAnnouncement(context.Context, *CreateAnnouncementRequest) (*CreateAnnouncementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAnnouncement not implemented")
}
func (UnimplementedAnnouncementsServer) AddImages(context.Context, *AddImagesRequest) (*AddImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddImages not implemented")
}
func (UnimplementedAnnouncementsServer) DeleteAnnouncement(context.Context, *DeleteAnnouncementRequest) (*DeleteAnnouncementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAnnouncement not implemented")
}
func (UnimplementedAnnouncementsServer) mustEmbedUnimplementedAnnouncementsServer() {}
func (UnimplementedAnnouncementsServer) testEmbeddedByValue()                       {}

// UnsafeAnnouncementsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnnouncementsServer will
// result in compilation errors.
type UnsafeAnnouncementsServer interface {
	mustEmbedUnimplementedAnnouncementsServer()
}

func RegisterAnnouncementsServer(s grpc.ServiceRegistrar, srv AnnouncementsServer) {
	// If the following call panics, it indicates UnimplementedAnnouncementsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Announcements_ServiceDesc, srv)
}

func _Announcements_SearchAnnouncements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchAnnouncementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnnouncementsServer).SearchAnnouncements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Announcements_SearchAnnouncements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnnouncementsServer).SearchAnnouncements(ctx, req.(*SearchAnnouncementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Announcements_CreateAnnouncement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAnnouncementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnnouncementsServer).CreateAnnouncement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Announcements_CreateAnnouncement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnnouncementsServer).CreateAnnouncement(ctx, req.(*CreateAnnouncementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Announcements_AddImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnnouncementsServer).AddImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Announcements_AddImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnnouncementsServer).AddImages(ctx, req.(*AddImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Announcements_DeleteAnnouncement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAnnouncementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnnouncementsServer).DeleteAnnouncement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Announcements_DeleteAnnouncement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnnouncementsServer).DeleteAnnouncement(ctx, req.(*DeleteAnnouncementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Announcements_ServiceDesc is the grpc.ServiceDesc for Announcements service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Announcements_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "announcements.Announcements",
	HandlerType: (*AnnouncementsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchAnnouncements",
			Handler:    _Announcements_SearchAnnouncements_Handler,
		},
		{
			MethodName: "CreateAnnouncement",
			Handler:    _Announcements_CreateAnnouncement_Handler,
		},
		{
			MethodName: "AddImages",
			Handler:    _Announcements_AddImages_Handler,
		},
		{
			MethodName: "DeleteAnnouncement",
			Handler:    _Announcements_DeleteAnnouncement_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "announcements.proto",
}
