// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0--rc1
// source: announcements.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Announcements_SearchAnnouncements_FullMethodName = "/announcements.Announcements/SearchAnnouncements"
	Announcements_CreateAnnouncement_FullMethodName  = "/announcements.Announcements/CreateAnnouncement"
	Announcements_AddImages_FullMethodName           = "/announcements.Announcements/AddImages"
	Announcements_DeleteAnnouncement_FullMethodName  = "/announcements.Announcements/DeleteAnnouncement"
)

// AnnouncementsClient is the client API for Announcements service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnnouncementsClient interface {
	SearchAnnouncements(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SearchAnnouncementsRequest, SearchAnnouncementsResponse], error)
	CreateAnnouncement(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CreateAnnouncementRequest, CreateAnnouncementResponse], error)
	AddImages(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AddImagesRequest, AddImagesResponse], error)
	DeleteAnnouncement(ctx context.Context, in *DeleteAnnouncementRequest, opts ...grpc.CallOption) (*DeleteAnnouncementResponse, error)
}

type announcementsClient struct {
	cc grpc.ClientConnInterface
}

func NewAnnouncementsClient(cc grpc.ClientConnInterface) AnnouncementsClient {
	return &announcementsClient{cc}
}

func (c *announcementsClient) SearchAnnouncements(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SearchAnnouncementsRequest, SearchAnnouncementsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Announcements_ServiceDesc.Streams[0], Announcements_SearchAnnouncements_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SearchAnnouncementsRequest, SearchAnnouncementsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Announcements_SearchAnnouncementsClient = grpc.ClientStreamingClient[SearchAnnouncementsRequest, SearchAnnouncementsResponse]

func (c *announcementsClient) CreateAnnouncement(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CreateAnnouncementRequest, CreateAnnouncementResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Announcements_ServiceDesc.Streams[1], Announcements_CreateAnnouncement_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CreateAnnouncementRequest, CreateAnnouncementResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Announcements_CreateAnnouncementClient = grpc.ClientStreamingClient[CreateAnnouncementRequest, CreateAnnouncementResponse]

func (c *announcementsClient) AddImages(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AddImagesRequest, AddImagesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Announcements_ServiceDesc.Streams[2], Announcements_AddImages_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AddImagesRequest, AddImagesResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Announcements_AddImagesClient = grpc.ClientStreamingClient[AddImagesRequest, AddImagesResponse]

func (c *announcementsClient) DeleteAnnouncement(ctx context.Context, in *DeleteAnnouncementRequest, opts ...grpc.CallOption) (*DeleteAnnouncementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAnnouncementResponse)
	err := c.cc.Invoke(ctx, Announcements_DeleteAnnouncement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnnouncementsServer is the server API for Announcements service.
// All implementations must embed UnimplementedAnnouncementsServer
// for forward compatibility.
type AnnouncementsServer interface {
	SearchAnnouncements(grpc.ClientStreamingServer[SearchAnnouncementsRequest, SearchAnnouncementsResponse]) error
	CreateAnnouncement(grpc.ClientStreamingServer[CreateAnnouncementRequest, CreateAnnouncementResponse]) error
	AddImages(grpc.ClientStreamingServer[AddImagesRequest, AddImagesResponse]) error
	DeleteAnnouncement(context.Context, *DeleteAnnouncementRequest) (*DeleteAnnouncementResponse, error)
	mustEmbedUnimplementedAnnouncementsServer()
}

// UnimplementedAnnouncementsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnnouncementsServer struct{}

func (UnimplementedAnnouncementsServer) SearchAnnouncements(grpc.ClientStreamingServer[SearchAnnouncementsRequest, SearchAnnouncementsResponse]) error {
	return status.Error(codes.Unimplemented, "method SearchAnnouncements not implemented")
}
func (UnimplementedAnnouncementsServer) CreateAnnouncement(grpc.ClientStreamingServer[CreateAnnouncementRequest, CreateAnnouncementResponse]) error {
	return status.Error(codes.Unimplemented, "method CreateAnnouncement not implemented")
}
func (UnimplementedAnnouncementsServer) AddImages(grpc.ClientStreamingServer[AddImagesRequest, AddImagesResponse]) error {
	return status.Error(codes.Unimplemented, "method AddImages not implemented")
}
func (UnimplementedAnnouncementsServer) DeleteAnnouncement(context.Context, *DeleteAnnouncementRequest) (*DeleteAnnouncementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAnnouncement not implemented")
}
func (UnimplementedAnnouncementsServer) mustEmbedUnimplementedAnnouncementsServer() {}
func (UnimplementedAnnouncementsServer) testEmbeddedByValue()                       {}

// UnsafeAnnouncementsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnnouncementsServer will
// result in compilation errors.
type UnsafeAnnouncementsServer interface {
	mustEmbedUnimplementedAnnouncementsServer()
}

func RegisterAnnouncementsServer(s grpc.ServiceRegistrar, srv AnnouncementsServer) {
	// If the following call panics, it indicates UnimplementedAnnouncementsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Announcements_ServiceDesc, srv)
}

func _Announcements_SearchAnnouncements_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AnnouncementsServer).SearchAnnouncements(&grpc.GenericServerStream[SearchAnnouncementsRequest, SearchAnnouncementsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Announcements_SearchAnnouncementsServer = grpc.ClientStreamingServer[SearchAnnouncementsRequest, SearchAnnouncementsResponse]

func _Announcements_CreateAnnouncement_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AnnouncementsServer).CreateAnnouncement(&grpc.GenericServerStream[CreateAnnouncementRequest, CreateAnnouncementResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Announcements_CreateAnnouncementServer = grpc.ClientStreamingServer[CreateAnnouncementRequest, CreateAnnouncementResponse]

func _Announcements_AddImages_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AnnouncementsServer).AddImages(&grpc.GenericServerStream[AddImagesRequest, AddImagesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Announcements_AddImagesServer = grpc.ClientStreamingServer[AddImagesRequest, AddImagesResponse]

func _Announcements_DeleteAnnouncement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAnnouncementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnnouncementsServer).DeleteAnnouncement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Announcements_DeleteAnnouncement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnnouncementsServer).DeleteAnnouncement(ctx, req.(*DeleteAnnouncementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Announcements_ServiceDesc is the grpc.ServiceDesc for Announcements service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Announcements_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "announcements.Announcements",
	HandlerType: (*AnnouncementsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteAnnouncement",
			Handler:    _Announcements_DeleteAnnouncement_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SearchAnnouncements",
			Handler:       _Announcements_SearchAnnouncements_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "CreateAnnouncement",
			Handler:       _Announcements_CreateAnnouncement_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "AddImages",
			Handler:       _Announcements_AddImages_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "announcements.proto",
}
